name: MoreSpearEnchantments
version: 1.1.1
main: dev.sillyangel.more_spear_enchantments.MoreSpearEnchantments
bootstrapper: dev.sillyangel.more_spear_enchantments.SpearEnchantmentsBootstrap
description: more enchantments for the newly added spear from the Mounts of Mayhem update
author: sillyangel
website: https://modrinth.com/mod/more-spear-enchantments
api-version: '1.21.11'

